<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.12.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PedroFarah.WFVendas.Dto\PedroFarah.WFVendas.Dto.csproj" />
    <ProjectReference Include="..\PedroFarah.WFVendas.Persistence\PedroFarah.WFVendas.Persistence.csproj" />
  </ItemGroup>

</Project>
